apiVersion: habana.ai/v1alpha1
kind: DeviceConfig
metadata:
  name: habana-ai-deviceconfig-instance
  namespace: habana-ai-operator
spec:
  driverImage: ghcr.io/fabiendupont/habana-ai-driver
  driverVersion: 1.6.0-439
  gaudiNodeSelector:
    habana.ai/hpu.gaudi.present: "true"
