apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-kernel-args-firmware-path
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
    - 'firmware_class.path=/var/lib/firmware'
