apiVersion: v1
kind: Pod
metadata:
  name: habana-ai-demo
  namespace: habana-ai-operator
spec:
  restartPolicy: OnFailure
  containers:
  - image: vault.habana.ai/gaudi-docker/1.6.1/ubuntu20.04/habanalabs/tensorflow-installer-tf-cpu-2.9.1:latest
    imagePullPolicy: IfNotPresent
    name: habana-ai-base-container
    command:
    - "hl-smi"
    args:
    - "-L"
    resources:
      limits:
        habana.ai/gaudi: "1"
    securityContext:
      capabilities:
        add:
          - "SYS_RAWIO"
