resources:
- manager.yaml

patchesStrategicMerge:
- patches/controller_image.yaml
- patches/env_images.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: manager-config
  files:
  - controller_manager_config.yaml
