---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: driver-habana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: driver-habana
subjects:
- kind: ServiceAccount
  name: driver-habana
