apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: habana-ai-operator.v99.0.0
  namespace: placeholder
spec:
  relatedImages:
    - name: device-plugin
      image: vault.habana.ai/docker-k8s-device-plugin/docker-k8s-device-plugin@sha256:8d26825a2745effc2592b80fa7b7127e9d844ae516379737ef137e0b7b07ad7c