name: Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Create kind cluster
      uses: helm/kind-action@v1.3.0

    - name: Install mockgen
      run: go install github.com/golang/mock/mockgen@v1.6.0

    - name: Run tests
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: cover.out
